config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :theaters
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reservations#index"
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id             :bigint           not null, primary key
#  content_choice :string
#  duration       :float
#  end_time       :datetime
#  number_guests  :integer
#  start_time     :datetime
#  status         :string           default("pending")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  theater_id     :integer
#  user_id        :integer
#
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :theater

  validate :validate_guests_less_than_seats
  validate :no_conflicting_reservations
  validate :start_time_must_be_in_the_future

  scope :upcoming_week, -> { 
    where(start_time: Time.zone.now..Time.zone.now + 7.days) 
  }

  scope :future, -> { where('start_time >= ?', Time.current) }
  scope :past, -> { where('end_time < ?', Time.current) }
  scope :current, -> { where('start_time <= ? AND end_time >= ?', Time.current, Time.current) }
  
  enum status: {
    pending: 'pending',
    confirmed: 'confirmed',
    cancelled: 'cancelled',
    completed: 'completed'
  }

  enum content_choice: {
    byoc: 'BYOC',
    physical: 'Physical',
    new_release: 'New Release',
  }

  def future_reservation?
    start_time >= Time.current
  end

  def content_choice_display
    case content_choice
    when 'byoc'
      'BYOC - Bring Your Own Content'
    when 'physical'
      'Physical'
    when 'new_release'
      'New Release'
    else
      'Unknown'
    end
  end

  private

  def validate_guests_less_than_seats
    if number_guests.present? && theater.present? && number_guests > theater.number_of_seats
      errors.add(:number_guests, "cannot be greater than the number of seats in the theater")
    end
  end

  def no_conflicting_reservations
    conflicting_reservations = Reservation.where(theater_id: theater_id)
                                         .where('start_time < ? AND end_time > ?', end_time, start_time)
    conflicting_reservations = conflicting_reservations.or(Reservation.where(theater_id: theater_id)
                                                                   .where('start_time = ? OR end_time = ?', start_time, end_time))
    conflicting_reservations = conflicting_reservations.where.not(id: id) if persisted?
    
    if conflicting_reservations.exists?
      errors.add(:base, "Conflicting reservation exists for this theater and time")
    end
  end

  def start_time_must_be_in_the_future
    errors.add(:start_time, "must be in the future") if start_time.present? && start_time < Time.current
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include CalendarHelper
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @theaters = Theater.all
    @reservations = Reservation.all.order(start_time: :desc)
    if params[:date].present?
      @selected_date = Date.parse(params[:date])
      @selected_datetime = @selected_date.to_time.in_time_zone('Central Time (US & Canada)')
      # Fetch reservations only for the selected date
    else
      @selected_date = Date.current
      @selected_datetime = @selected_date.to_time.in_time_zone('Central Time (US & Canada)')
    end
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @theaters = Theater.all
    @reservation = Reservation.new
    @reservation.start_time = params[:start_time]
    @reservation.end_time = params[:end_time]
    @reservation.theater_id = params[:theater_id]
    if @reservation.start_time.nil?
      if params[:date].present?
        @selected_date = Date.parse(params[:date])
        if @selected_date < Date.current
          flash.now[:alert] = "Unless you have a time machine, reservations cannot be made for the past."
          @selected_date = Date.current
        end
      else
        @selected_date = Date.current
      end
    else
      @selected_date = @reservation.start_time.to_date
    end
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = current_user.reservations.build(reservation_params)
    @reservation.duration = (@reservation.end_time - @reservation.start_time)/60

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        @theaters = Theater.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    @reservation = current_user.reservations.find(params[:id])

    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :theater_id, :status, :start_time, :end_time, :duration, :number_guests, :content_choice)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_admin_table.html.erb
<table class="table-calendar">
  <thead>
    <tr>
      <th>
        Theater
      </th>
      <th>
        User (Need names)
      </th>
      <th>
        Start DateTime
      </th>
      <th>
        End DateTime
      </th>
      <th>
        Status
      </th>
      <th>
        Edit
      </th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
          Theater <%= reservation.theater.id %>
        </td>
        <td>
          User <%= reservation.user.id%>
        </td>            
        <td>
          <%= reservation.start_time.strftime("%b %d, %Y - %l:%M %p") %>
        </td>
        <td>
          <%= reservation.end_time.strftime("%b %d, %Y - %l:%M %p") %>
        </td>
        <td>
          <%= reservation.status %>
        </td>        
        <td>
          <div class="d-flex justify-content-center align-items-center">
            <%= link_to "See Reservation", reservation_path(reservation), class: 'btn btn-primary', style: '--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .5rem;'%>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>

  <div>
    <%= form.hidden_field :theater_id %>
  </div>

  <div>
    <%= form.hidden_field :status %>
  </div>

  <div>
    <%= form.hidden_field :start_time %>
  </div>

  <div>
    <%= form.hidden_field :end_time %>
  </div>

  <% if @reservation.end_time %>
    <div class="row">
      <div class="col-md-3">
        <%= form.label :number_guests, "Number of Guests", class: 'form-label' %>
        <%= form.select :number_guests, options_for_select(1..reservation.theater.number_of_seats), {}, class: 'form-select' %>
      </div>
      <div class="col-md-9">
        <%= form.label :content_choice, class: 'form-label' %>
        <%= form.select :content_choice, options_for_select(Reservation.content_choices.map { |key, _| [Reservation.new(content_choice: key).content_choice_display, key] }, @reservation.content_choice), {}, class: 'form-select' %>
      </div>
    </div>
  <% end %>

  <% if @reservation.end_time %>
    <div class="d-flex justify-content-end mt-3">
      <button type="submit" class="btn btn-primary">
        Continue to Payment 
        <%= content_tag(:i, '', class: 'fa-solid fa-arrow-right', style: 'color: #ffffff;') %>
      </button>
    </div>
  <% end %>
<% end %>

app/views/reservations/_reservation.html.erb
<div class="col">
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title" align="center">
        <%= reservation.start_time.strftime("%B %e, %Y at %l:%M %p")%>
      </h5>
      <p class="card-text">
        <ul style="list-style-type: none">
          <li><strong>Start Time:</strong> <%= reservation.start_time.strftime("%l:%M %p")%></li>
          <li><strong>End Time:</strong> <%= reservation.end_time.strftime("%l:%M %p")%></li>
          <li><strong>Number of Guests:</strong> <%= reservation.number_guests%></li>
          <li><strong>Content Choice:</strong> <%= reservation.content_choice.humanize%></li>
          <li><strong>Theater:</strong> <%= reservation.theater_id %></li>
          <li><strong>User:</strong> <%= reservation.user_id %></li>
          <li><strong>Status:</strong> <%= reservation.status %></li>
        </ul>
      </p>
      <% if reservation.future_reservation? %>
        <div class="d-grid gap-2">
          <%= link_to "Update Reservation", edit_reservation_path(reservation), class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/_schedule.html.erb
<div class="table-container">
  <table class="table-calendar">
    <thead>
      <tr>
        <th scope="col">Time</th>
        <% @theaters.each do |theater| %>
          <th scope="col">Theater <%= theater.id %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% (10..23).each do |hour| %>
        <% (0..3).each do |quarter| %>
          <% time = @selected_datetime.in_time_zone.change(hour: hour, min: quarter * 15) %>
          <% next_time = time + 15.minutes %>
          <tr>
            <th scope="row">
              <%= time.strftime("%l:%M %p - ") %>
              <%= next_time.strftime("%l:%M %p") %>
            </th>
            <% @theaters.each do |theater| %>
              <td>
                <% if !theater.interval_reserved?(time.hour, time.min / 15, @selected_date) %>
                  Available
                <% else %>
                  <% reservation = theater.find_reservation_for_interval(time.hour, time.min / 15, @selected_date) %>
                  <%= link_to "#{reservation.start_time.strftime("%l:%M %p - ")} #{reservation.end_time.strftime("%l:%M %p")}" , reservation_path(reservation), class: 'btn btn-primary', style: '--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .5rem;'%>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>



<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<div class="mt-4">
  <h1>Reservations</h1>

  <% if current_user == nil %>
    <p>Sign in to make a reservation</p>
  <% else %>
    <% if current_user.user_type == "standard" %>
      <%= link_to "New reservation", new_reservation_path %>

      <%# CURRENT RESERVATIONS%>
      <% if current_user.reservations.current.any? %>
        <h2>Current Reservation</h2>
        <div class="row row-cols-1 row-cols-md-3 g-4">
          <% current_user.reservations.current.each do |reservation| %>
            <%= render reservation %>
          <% end %>
        </div>
      <% end %>

      <%# FUTURE RESERVATIONS %>
      <% if current_user.reservations.future.any? %>
        <h2>Upcoming Reservations</h2>
        <div class="row row-cols-1 row-cols-md-3 g-4">
          <% current_user.reservations.future.each do |reservation| %>
            <%= render reservation %>
          <% end %>
        </div>
      <% end %>

      <%# PAST RESERVATIONS %>
      <% if current_user.reservations.past.any? %>
        <h2>Previous Reservations</h2>
        <div class="row row-cols-1 row-cols-md-3 g-4">
          <% current_user.reservations.past.each do |reservation| %>
            <%= render reservation %>
          <% end %>
        </div>
      <% end %>

    <% elsif current_user.user_type == "admin" %>
      <div class="mt-4">
        <h3>Admin View</h2>
      </div>


      <div class="mt-4">
        <h4>
          Schedule
        </h4>
      </div>

      <div class="d-flex justify-content-center mt-3 mb-3">
        <%= form_tag(reservations_path, method: :get) do %>
          <%= label_tag "Select Date: " %>
          <%= date_field_tag :date, @selected_date %>
          <%= submit_tag "See Availability", class: 'btn btn-primary', style: '--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;'%>
        <% end %>
      </div>

      <div><%= render "schedule" %></div>

      <div class="mt-4">
        <h4>
          Table
        </h4>
      </div>    
      <div class="mb-4">
        <%= render "admin_table" %>
      </div>
      
    <% end %>
  <% end %>
</div>

app/views/reservations/new.html.erb
<!-- Error Message -->
<% if @reservation.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show mt-4" role="alert">
    <strong><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</strong> 
    <ul>
      <% @reservation.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="col-md-6 offset-md-3 mt-4">
  <h1>Make a reservation</h1>
</div>

<div>
  Current Time: <%= Time.current.strftime("%l:%M %p %b %d") %>
</div>

<div class="d-flex justify-content-center mt-3 mb-3">
  <%= form_tag(new_reservation_path, method: :get) do %>
    <%= label_tag "Select Date: " %>
    <%= date_field_tag :date, @selected_date %>
    <%= submit_tag "See Availability", class: 'btn btn-primary', style: '--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;'%>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <% if @selected_date < Date.current %>
        ADD AN ERROR MESSAGE SO THAT THEY HAVE TO PICK A FUTURE DATE
      <% else %>
        <% if @reservation.start_time %>
          <div>1. Start Time: <%= @reservation.start_time.strftime("%l:%M %p") if @reservation.start_time %> </div>
          <% if @reservation.end_time %>
            <div>2. End Time: <%= @reservation.end_time.strftime("%l:%M %p") if @reservation.end_time %> </div>
            <%= render "shared/calendar", start_time: @reservation.start_time, end_time: @reservation.end_time, theater_id: @reservation.theater_id  %>
            <div class="mt-2 mb-2"><strong>3. Fill out the remainder of your reservation.</strong></div>
            <div>
              <%= render "form", reservation: @reservation %>
            </div>
          <% else %>
            <div><strong>2. Select an available time for the end of your reservation.</strong></div>
            <%= render "shared/calendar", start_time: @reservation.start_time, end_time: @reservation.end_time, theater_id: @reservation.theater_id  %>
          <% end %>
        <% else %>
          <div><strong>1. Select an available time for the start of your reservation.</strong></div>
          <%= render "shared/calendar", start_time: @reservation.start_time, end_time: @reservation.end_time, theater_id: @reservation.theater_id, date: @selected_date %>
        <% end %></strong>
      <% end %>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<%= link_to "Back to reservations", reservations_path %>

<p>Need to add restrictions to admins and users only</p>

<%= render @reservation %>