config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :theaters
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reservations#index"
end

app/models/theater.rb
# == Schema Information
#
# Table name: theaters
#
#  id                 :bigint           not null, primary key
#  number_of_seats    :integer
#  reservations_count :integer
#  turnover_time      :float
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Theater < ApplicationRecord
  has_many  :reservations, dependent: :nullify

  def reservations_for_date(date)
    self.reservations.where(start_time: date.beginning_of_day..date.end_of_day)
  end

  def interval_reserved?(hour, quarter, date)
    start_time = date.in_time_zone.change(hour: hour, min: quarter * 15)
    end_time = start_time + 15.minutes
  
    reservations.where("start_time < ? AND end_time > ?", end_time, start_time).exists?
  end

  def next_reservation_after(time)
    reservations.where("start_time >= ?", time).order(:start_time).first
  end

  def find_reservation_for_interval(hour, quarter, date)
    start_time = date.in_time_zone.change(hour: hour, min: quarter * 15)
    end_time = start_time + 15.minutes

    reservations.find_by("start_time < ? AND end_time > ?", end_time, start_time)
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: %i[ show edit update destroy ]

  # GET /theaters or /theaters.json
  def index
    @theaters = Theater.all
  end

  # GET /theaters/1 or /theaters/1.json
  def show
  end

  # GET /theaters/new
  def new
    @theater = Theater.new
  end

  # GET /theaters/1/edit
  def edit
  end

  # POST /theaters or /theaters.json
  def create
    @theater = Theater.new(theater_params)

    respond_to do |format|
      if @theater.save
        format.html { redirect_to theater_url(@theater), notice: "Theater was successfully created." }
        format.json { render :show, status: :created, location: @theater }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theaters/1 or /theaters/1.json
  def update
    respond_to do |format|
      if @theater.update(theater_params)
        format.html { redirect_to theater_url(@theater), notice: "Theater was successfully updated." }
        format.json { render :show, status: :ok, location: @theater }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1 or /theaters/1.json
  def destroy
    @theater.destroy

    respond_to do |format|
      format.html { redirect_to theaters_url, notice: "Theater was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theater
      @theater = Theater.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theater_params
      params.require(:theater).permit(:number_of_seats, :turnover_time, :reservations_count)
    end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_availability.html.erb
<h3>
  Theater availability
</h3>

<div id="theaters">
  <ul>
    <% @theaters.each do |theater| %>
      <li><%= theater.id %></li>
    <% end %>
  </ul>
</div>

app/views/theaters/_availability_form.html.erb
<%= form_with(model: theater, url: theaters_availability_path, method: :get) do |form| %>
  <%= form.label :date, "Select a Date:" %>
  <%= form.date_field :date %>
  <%= form.submit "Check Availability" %>
<% end %>

app/views/theaters/_form.html.erb
<%= form_with(model: theater) do |form| %>
  <% if theater.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
        <% theater.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number_of_seats, style: "display: block" %>
    <%= form.number_field :number_of_seats %>
  </div>

  <div>
    <%= form.label :turnover_time, style: "display: block" %>
    <%= form.text_field :turnover_time %>
  </div>

  <div>
    <%= form.label :reservations_count, style: "display: block" %>
    <%= form.number_field :reservations_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/theaters/_theater.html.erb
<div id="<%= dom_id theater %>">

  <h2>All Reservations For Today:</h2>
  <% if theater.reservations_for_date(Date.today).any? %>
    <ul>
      <% theater.reservations_for_date(Date.today).each do |reservation|%>
        <li><%= reservation.start_time.strftime("%B %d, %Y %I:%M %p") %> and <%= reservation.end_time.strftime("%B %d, %Y %I:%M %p") %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No reservations for this theater.</p>
  <% end %>

  <p>
    <strong>Number of seats:</strong>
    <%= theater.number_of_seats %>
  </p>

  <p>
    <strong>Turnover time:</strong>
    <%= theater.turnover_time %>
  </p>

  <p>
    <strong>Reservations count:</strong>
    <%= theater.reservations_count %>
  </p>
</div>

app/views/theaters/edit.html.erb
<h1>Editing theater</h1>

<%= render "form", theater: @theater %>

<br>

<div>
  <%= link_to "Show this theater", @theater %> |
  <%= link_to "Back to theaters", theaters_path %>
</div>

app/views/theaters/index.html.erb
<h1>Theaters</h1>

<div>
  <h1>Don't want to delete this yet.</h1>
</div>

<div id="theaters">
  <% @theaters.each do |theater| %>
    <%= render theater %>
    <p>
      <%= link_to "Show this theater", theater %>
    </p>
  <% end %>
</div>

<%= link_to "New theater", new_theater_path %>

app/views/theaters/new.html.erb
<h1>New theater</h1>

<%= render "form", theater: @theater %>

<br>

<div>
  <%= link_to "Back to theaters", theaters_path %>
</div>

app/views/theaters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @theater %>

<div>
  <%= link_to "Edit this theater", edit_theater_path(@theater) %> |
  <%= link_to "Back to theaters", theaters_path %>

  <%= button_to "Destroy this theater", @theater, method: :delete %>
</div>